#!/usr/bin/env bash
set -x

apt install -yy ntp ntpstat

/usr/bin/apt-key adv \
        --keyserver hkp://p80.pool.sks-keyservers.net:80 \
        --recv-keys 58118E89F3A912897C070ADBF76221572C52609D
    echo "deb https://apt.dockerproject.org/repo ubuntu-$(lsb_release -sc) main" > /etc/apt/sources.list.d/docker.list
apt-get update
apt-get install -yy docker-engine=1.12.*

docker run -d -p 8080:8080 --name http-server wibniwibni/node-hello-world

! getent passwd ubuntu || usermod -a -G docker ubuntu
